# Generated by Django 5.1.3 on 2024-11-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stockquote',
            managers=[
            ],
        ),
    ]
