# Generated by Django 5.1.3 on 2024-11-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_stockquote_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockquote',
            unique_together={('company', 'time')},
        ),
    ]
